#!/usr/bin/env python3
"""Generate index/INDEX.md and index/skills.json from skill folders and catalog.json."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "catalog.json"
INDEX_DIR = ROOT / "index"
INDEX_MD = INDEX_DIR / "INDEX.md"
INDEX_JSON = INDEX_DIR / "skills.json"

NAME_RE = re.compile(r"^name:\s*(.+)$", re.MULTILINE)
DESC_RE = re.compile(r"^description:\s*(.+)$", re.MULTILINE)
VERSION_RE = re.compile(r"^version:\s*(.+)$", re.MULTILINE)
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def parse_frontmatter(text: str) -> dict[str, str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}
    fields: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if ":" not in line or line.strip().startswith("#"):
            continue
        k, v = line.split(":", 1)
        fields[k.strip()] = v.strip().strip('"').strip("'")
    return fields


def main() -> int:
    if not CATALOG_PATH.is_file():
        print(f"error: catalog not found at {CATALOG_PATH}", file=sys.stderr)
        return 1
    catalog = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    packages = catalog.get("packages", {})
    skills = catalog.get("skills", [])

    entries = []
    for s in skills:
        name = s.get("name", "")
        path = s.get("path", "")
        skill_md = ROOT / path / "SKILL.md"
        fm = parse_frontmatter(skill_md.read_text(encoding="utf-8")) if skill_md.is_file() else {}
        entries.append({
            "id": s.get("id", name),
            "name": name,
            "package": s.get("package", ""),
            "path": path,
            "version": s.get("version") or fm.get("version") or "",
            "description": s.get("description") or fm.get("description") or "",
            "has_scripts": (ROOT / path / "scripts").is_dir(),
            "has_references": (ROOT / path / "references").is_dir(),
        })

    INDEX_DIR.mkdir(parents=True, exist_ok=True)
    INDEX_JSON.write_text(
        json.dumps({"generated_by": "scripts/build-index.py", "skills": entries},
                   indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    lines = [
        "# Ottili ONE Skills Index",
        "",
        f"Generated by `scripts/build-index.py`. {len(entries)} skills.",
        "",
        "## Packages",
        "",
    ]
    for pkg in packages.values():
        lines.append(f"- `{pkg.get('name', '')}` ({pkg.get('path', '')})")
    lines += ["", "## Skills", "", "| Name | Package | Version | Description |", "|------|----------|---------|-------------|"]
    for e in entries:
        desc = (e["description"] or "").replace("|", "\\|")
        lines.append(f"| [{e['name']}]({e['path']}) | {e['package']} | {e['version'] or '—'} | {desc[:120]} |")
    lines += ["", "## Machine-readable", "", "`index/skills.json`."]
    INDEX_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"ok: wrote {INDEX_MD} and {INDEX_JSON} ({len(entries)} skills)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
